name: storyline
channels:
  - conda-forge
dependencies:
  - python=3.12.9
  - ipywidgets
  - ipykernel
  - jupyterlab
  - matplotlib
  - networkx
  - nltk
  - pandas
  - plotly
  - seaborn
  - pillow
  - fpdf2
